### ISSUE TITLE
Type 'RTCCameraVideoCapturer' has no member 'format' Swift 4.2

### ISSUE THREAD

**Issue by saroar** [kurzdigital/WAL#1] opened 2019-01-13 17:31 UTC
http://prntscr.com/m6nm5f

from this code 

```
let format = RTCCameraVideoCapturer.format(
            for: device,
            constraints: config.formatConstraints)
```

file name `WebRTCConnection.swift`

error -> Type 'RTCCameraVideoCapturer' has no member 'format'
Swift Version 4.2 

how i can fixed it

**Comment by saroar** [comment] 2019-01-13 18:05
not working or real device but work on simulator :(

**Comment by ChristianNorbertBraun** [comment] 2019-01-14 09:51
Hi there,
I'm unable to reproduce your problem.
You could try to run `pod update` again. 
Please post the dependency versions from the Podfile.lock.

Could you check out our [Whale Demo Project](https://github.com/kurzdigital/Whale) and follow the instructions from the README.md to reproduce the error?

**Comment by saroar** [comment] 2019-01-14 10:36
i think its webRTC problem not ur Demo Project

**Comment by ChristianNorbertBraun** [comment] 2019-01-14 13:11
As I can't reproduce the problem and the Demo projects seems to be working I close this issue.

**Closed as completed by ChristianNorbertBraun** 2019-01-14 13:11 UTC
